MechanicCatalog = {}

MechanicCatalog.ComponentOrder = {
    'engine_block',
    'cooling_system',
    'ignition_system',
    'gearbox',
    'clutch_assembly',
    'brake_system',
    'suspension_kit',
    'drivetrain',
    'tires',
    'body_structure',
    'fuel_system',
    'ecu_unit',
    'turbocharger',
}

MechanicCatalog.Components = {
    engine_block = {
        label = 'Bloco do motor',
        category = 'powertrain',
        description = 'Compressao, bielas, pistoes e integridade do bloco principal.',
        weight = 1.60,
        repairThreshold = 46,
        repairHours = 3.8,
        replaceHours = 7.2,
        severity = 'extreme',
        unitCost = 18500,
        replacementItem = 'engine_block',
        repairItems = { gasket_set = 1, lubricant = 2, fastener_kit = 1 },
        replaceItems = { engine_block = 1, gasket_set = 2, lubricant = 3, fastener_kit = 1 },
        wearChannels = {
            mileage = 0.62,
            collision = 0.24,
            burnout = 0.30,
            braking = 0.02,
            offroad = 0.12,
            heat = 0.46,
            drift = 0.18,
            landing = 0.22,
        },
        effects = {
            enginePowerLoss = 0.42,
            torqueLoss = 0.32,
            stallRisk = 0.18,
        },
    },
    cooling_system = {
        label = 'Sistema de arrefecimento',
        category = 'cooling',
        description = 'Radiador, mangueiras, bomba dagua e controle termico.',
        weight = 1.15,
        repairThreshold = 44,
        repairHours = 2.6,
        replaceHours = 4.5,
        severity = 'high',
        unitCost = 6200,
        replacementItem = 'cooling_system',
        repairItems = { coolant = 2, clamp_kit = 1, gasket_set = 1 },
        replaceItems = { cooling_system = 1, coolant = 3, clamp_kit = 1 },
        wearChannels = {
            mileage = 0.34,
            collision = 0.12,
            burnout = 0.05,
            braking = 0.00,
            offroad = 0.11,
            heat = 0.58,
            drift = 0.02,
            landing = 0.10,
        },
        effects = {
            overheatRisk = 0.48,
            enginePowerLoss = 0.16,
        },
    },
    ignition_system = {
        label = 'Sistema de ignicao',
        category = 'electrical',
        description = 'Bobinas, velas, sincronismo de ignicao e entrega de centelha.',
        weight = 0.85,
        repairThreshold = 50,
        repairHours = 1.8,
        replaceHours = 3.1,
        severity = 'medium',
        unitCost = 3400,
        replacementItem = 'ignition_system',
        repairItems = { wiring_kit = 1, ignition_parts = 1 },
        replaceItems = { ignition_system = 1, wiring_kit = 1, ignition_parts = 2 },
        wearChannels = {
            mileage = 0.24,
            collision = 0.06,
            burnout = 0.14,
            braking = 0.01,
            offroad = 0.05,
            heat = 0.31,
            drift = 0.06,
            landing = 0.02,
        },
        effects = {
            stallRisk = 0.22,
            enginePowerLoss = 0.11,
        },
    },
    gearbox = {
        label = 'Caixa de cambio',
        category = 'transmission',
        description = 'Engrenagens, sincronizadores e relacoes de marcha.',
        weight = 1.40,
        repairThreshold = 42,
        repairHours = 3.4,
        replaceHours = 6.1,
        severity = 'high',
        unitCost = 11200,
        replacementItem = 'gearbox',
        repairItems = { transmission_fluid = 2, fastener_kit = 1, alignment_shims = 1 },
        replaceItems = { gearbox = 1, transmission_fluid = 3, fastener_kit = 1, alignment_shims = 1 },
        wearChannels = {
            mileage = 0.48,
            collision = 0.10,
            burnout = 0.28,
            braking = 0.03,
            offroad = 0.10,
            heat = 0.21,
            drift = 0.24,
            landing = 0.18,
        },
        effects = {
            shiftDelay = 0.42,
            enginePowerLoss = 0.14,
        },
    },
    clutch_assembly = {
        label = 'Conjunto de embreagem',
        category = 'transmission',
        description = 'Disco, plato e resposta de acoplamento.',
        weight = 1.05,
        repairThreshold = 48,
        repairHours = 2.1,
        replaceHours = 3.8,
        severity = 'high',
        unitCost = 5100,
        replacementItem = 'clutch_assembly',
        repairItems = { lubricant = 1, fastener_kit = 1, clutch_plate = 1 },
        replaceItems = { clutch_assembly = 1, lubricant = 1, fastener_kit = 1, clutch_plate = 1 },
        wearChannels = {
            mileage = 0.44,
            collision = 0.02,
            burnout = 0.40,
            braking = 0.02,
            offroad = 0.04,
            heat = 0.18,
            drift = 0.22,
            landing = 0.05,
        },
        effects = {
            shiftDelay = 0.22,
            torqueLoss = 0.18,
        },
    },
    brake_system = {
        label = 'Sistema de freios',
        category = 'braking',
        description = 'Discos, pastilhas, linhas e eficiencia de frenagem.',
        weight = 1.25,
        repairThreshold = 52,
        repairHours = 1.9,
        replaceHours = 3.2,
        severity = 'critical',
        unitCost = 4800,
        replacementItem = 'brake_system',
        repairItems = { brake_fluid = 1, brake_pad_set = 1 },
        replaceItems = { brake_system = 1, brake_fluid = 2, brake_pad_set = 2 },
        wearChannels = {
            mileage = 0.31,
            collision = 0.04,
            burnout = 0.03,
            braking = 0.56,
            offroad = 0.08,
            heat = 0.14,
            drift = 0.08,
            landing = 0.09,
        },
        effects = {
            brakeLoss = 0.45,
            steeringLoss = 0.10,
        },
    },
    suspension_kit = {
        label = 'Suspensao',
        category = 'handling',
        description = 'Amortecedores, molas, buchas e geometria de rodagem.',
        weight = 1.20,
        repairThreshold = 50,
        repairHours = 2.4,
        replaceHours = 4.0,
        severity = 'high',
        unitCost = 5400,
        replacementItem = 'suspension_kit',
        repairItems = { alignment_shims = 1, fastener_kit = 1, lubricant = 1 },
        replaceItems = { suspension_kit = 1, alignment_shims = 2, fastener_kit = 1 },
        wearChannels = {
            mileage = 0.22,
            collision = 0.12,
            burnout = 0.01,
            braking = 0.08,
            offroad = 0.36,
            heat = 0.04,
            drift = 0.16,
            landing = 0.34,
        },
        effects = {
            gripLoss = 0.24,
            steeringLoss = 0.16,
        },
    },
    drivetrain = {
        label = 'Diferencial e carda',
        category = 'transmission',
        description = 'Transferencia de torque para o eixo motriz.',
        weight = 1.08,
        repairThreshold = 45,
        repairHours = 2.8,
        replaceHours = 4.9,
        severity = 'high',
        unitCost = 7600,
        replacementItem = 'drivetrain',
        repairItems = { transmission_fluid = 1, fastener_kit = 1, bearing_set = 1 },
        replaceItems = { drivetrain = 1, transmission_fluid = 2, bearing_set = 1, fastener_kit = 1 },
        wearChannels = {
            mileage = 0.36,
            collision = 0.08,
            burnout = 0.32,
            braking = 0.02,
            offroad = 0.18,
            heat = 0.11,
            drift = 0.22,
            landing = 0.21,
        },
        effects = {
            torqueLoss = 0.26,
            gripLoss = 0.08,
        },
    },
    tires = {
        label = 'Pneus',
        category = 'handling',
        description = 'Borracha, parede lateral, pressao e aderencia.',
        weight = 1.30,
        repairThreshold = 58,
        repairHours = 1.4,
        replaceHours = 2.3,
        severity = 'high',
        unitCost = 3200,
        replacementItem = 'tires',
        repairItems = { tire_sealant = 1, balancing_weight = 1 },
        replaceItems = { tires = 1, balancing_weight = 1 },
        wearChannels = {
            mileage = 0.42,
            collision = 0.06,
            burnout = 0.52,
            braking = 0.18,
            offroad = 0.26,
            heat = 0.09,
            drift = 0.44,
            landing = 0.14,
        },
        effects = {
            gripLoss = 0.52,
            steeringLoss = 0.12,
        },
    },
    body_structure = {
        label = 'Estrutura e carroceria',
        category = 'bodywork',
        description = 'Longarinas, paineis, acabamento e rigidez estrutural.',
        weight = 0.95,
        repairThreshold = 40,
        repairHours = 3.0,
        replaceHours = 5.6,
        severity = 'critical',
        unitCost = 9100,
        replacementItem = 'body_structure',
        repairItems = { chassis_weld = 2, body_filler = 2, fastener_kit = 1 },
        replaceItems = { body_structure = 1, chassis_weld = 2, body_filler = 2, fastener_kit = 1 },
        wearChannels = {
            mileage = 0.08,
            collision = 0.54,
            burnout = 0.00,
            braking = 0.02,
            offroad = 0.16,
            heat = 0.00,
            drift = 0.03,
            landing = 0.28,
        },
        effects = {
            bodyLoss = 0.48,
            steeringLoss = 0.08,
        },
    },
    fuel_system = {
        label = 'Sistema de combustivel',
        category = 'powertrain',
        description = 'Bomba, linhas, bicos e pressurizacao da mistura.',
        weight = 0.82,
        repairThreshold = 49,
        repairHours = 2.0,
        replaceHours = 3.6,
        severity = 'medium',
        unitCost = 4300,
        replacementItem = 'fuel_system',
        repairItems = { fuel_filter = 1, clamp_kit = 1, wiring_kit = 1 },
        replaceItems = { fuel_system = 1, fuel_filter = 1, clamp_kit = 1, wiring_kit = 1 },
        wearChannels = {
            mileage = 0.30,
            collision = 0.11,
            burnout = 0.04,
            braking = 0.00,
            offroad = 0.08,
            heat = 0.19,
            drift = 0.04,
            landing = 0.03,
        },
        effects = {
            enginePowerLoss = 0.14,
            stallRisk = 0.16,
        },
    },
    ecu_unit = {
        label = 'ECU e sensores',
        category = 'electrical',
        description = 'Central eletronica, sensores e calibracao de mapa.',
        weight = 0.88,
        repairThreshold = 54,
        repairHours = 1.6,
        replaceHours = 2.8,
        severity = 'medium',
        unitCost = 5900,
        replacementItem = 'ecu_unit',
        repairItems = { wiring_kit = 1, ecu_map_token = 1 },
        replaceItems = { ecu_unit = 1, wiring_kit = 1, ecu_map_token = 1 },
        wearChannels = {
            mileage = 0.20,
            collision = 0.14,
            burnout = 0.03,
            braking = 0.00,
            offroad = 0.04,
            heat = 0.18,
            drift = 0.03,
            landing = 0.02,
        },
        effects = {
            enginePowerLoss = 0.12,
            shiftDelay = 0.10,
        },
    },
    turbocharger = {
        label = 'Turbo e pressurizacao',
        category = 'powertrain',
        description = 'Turbina, pressao, dutos e spool do conjunto forjado.',
        weight = 0.74,
        repairThreshold = 47,
        repairHours = 2.2,
        replaceHours = 4.1,
        severity = 'high',
        unitCost = 9900,
        replacementItem = 'turbocharger',
        repairItems = { turbo_core = 1, lubricant = 1, clamp_kit = 1 },
        replaceItems = { turbocharger = 1, turbo_core = 1, lubricant = 2, clamp_kit = 1 },
        wearChannels = {
            mileage = 0.25,
            collision = 0.03,
            burnout = 0.10,
            braking = 0.00,
            offroad = 0.05,
            heat = 0.46,
            drift = 0.09,
            landing = 0.04,
        },
        effects = {
            enginePowerLoss = 0.24,
            overheatRisk = 0.18,
        },
    },
}

MechanicCatalog.StockItems = {
    engine_block = { label = 'Bloco do motor OEM', type = 'component', unitCost = 18500, defaultQuantity = 2, minimumStock = 1 },
    cooling_system = { label = 'Kit de arrefecimento', type = 'component', unitCost = 6200, defaultQuantity = 3, minimumStock = 1 },
    ignition_system = { label = 'Kit de ignicao', type = 'component', unitCost = 3400, defaultQuantity = 4, minimumStock = 1 },
    gearbox = { label = 'Caixa de cambio', type = 'component', unitCost = 11200, defaultQuantity = 2, minimumStock = 1 },
    clutch_assembly = { label = 'Kit de embreagem', type = 'component', unitCost = 5100, defaultQuantity = 4, minimumStock = 1 },
    brake_system = { label = 'Conjunto de freios', type = 'component', unitCost = 4800, defaultQuantity = 5, minimumStock = 2 },
    suspension_kit = { label = 'Kit de suspensao', type = 'component', unitCost = 5400, defaultQuantity = 4, minimumStock = 1 },
    drivetrain = { label = 'Diferencial e carda', type = 'component', unitCost = 7600, defaultQuantity = 3, minimumStock = 1 },
    tires = { label = 'Jogo de pneus', type = 'component', unitCost = 3200, defaultQuantity = 8, minimumStock = 2 },
    body_structure = { label = 'Painel estrutural', type = 'component', unitCost = 9100, defaultQuantity = 2, minimumStock = 1 },
    fuel_system = { label = 'Sistema de combustivel', type = 'component', unitCost = 4300, defaultQuantity = 4, minimumStock = 1 },
    ecu_unit = { label = 'ECU programavel', type = 'component', unitCost = 5900, defaultQuantity = 3, minimumStock = 1 },
    turbocharger = { label = 'Conjunto turbo', type = 'component', unitCost = 9900, defaultQuantity = 2, minimumStock = 1 },
    gasket_set = { label = 'Jogo de juntas', type = 'material', unitCost = 220, defaultQuantity = 15, minimumStock = 3 },
    lubricant = { label = 'Lubrificante sintetico', type = 'fluid', unitCost = 90, defaultQuantity = 24, minimumStock = 6 },
    fastener_kit = { label = 'Kit de fixacao', type = 'material', unitCost = 80, defaultQuantity = 30, minimumStock = 8 },
    coolant = { label = 'Aditivo premium', type = 'fluid', unitCost = 110, defaultQuantity = 20, minimumStock = 5 },
    clamp_kit = { label = 'Abracadeiras e conexoes', type = 'material', unitCost = 65, defaultQuantity = 18, minimumStock = 4 },
    ignition_parts = { label = 'Velas e bobinas', type = 'material', unitCost = 260, defaultQuantity = 12, minimumStock = 3 },
    transmission_fluid = { label = 'Fluido de transmissao', type = 'fluid', unitCost = 120, defaultQuantity = 16, minimumStock = 4 },
    alignment_shims = { label = 'Calcos de alinhamento', type = 'material', unitCost = 70, defaultQuantity = 18, minimumStock = 4 },
    clutch_plate = { label = 'Disco de embreagem', type = 'material', unitCost = 390, defaultQuantity = 10, minimumStock = 2 },
    brake_fluid = { label = 'Fluido de freio DOT', type = 'fluid', unitCost = 95, defaultQuantity = 18, minimumStock = 4 },
    brake_pad_set = { label = 'Pastilhas esportivas', type = 'material', unitCost = 280, defaultQuantity = 12, minimumStock = 3 },
    bearing_set = { label = 'Jogo de rolamentos', type = 'material', unitCost = 240, defaultQuantity = 10, minimumStock = 2 },
    tire_sealant = { label = 'Selante de pneu', type = 'material', unitCost = 65, defaultQuantity = 16, minimumStock = 4 },
    balancing_weight = { label = 'Pesos de balanceamento', type = 'material', unitCost = 35, defaultQuantity = 24, minimumStock = 6 },
    chassis_weld = { label = 'Carga de solda estrutural', type = 'material', unitCost = 210, defaultQuantity = 10, minimumStock = 2 },
    body_filler = { label = 'Composto de acabamento', type = 'material', unitCost = 85, defaultQuantity = 14, minimumStock = 4 },
    fuel_filter = { label = 'Filtro de combustivel', type = 'material', unitCost = 130, defaultQuantity = 16, minimumStock = 3 },
    wiring_kit = { label = 'Chicote e conectores', type = 'material', unitCost = 175, defaultQuantity = 14, minimumStock = 3 },
    ecu_map_token = { label = 'Licenca de remapeamento', type = 'service', unitCost = 520, defaultQuantity = 10, minimumStock = 2 },
    turbo_core = { label = 'Miolo de turbina', type = 'component', unitCost = 1350, defaultQuantity = 6, minimumStock = 2 },
    performance_filter = { label = 'Filtro de alto fluxo', type = 'component', unitCost = 290, defaultQuantity = 10, minimumStock = 2 },
}

MechanicCatalog.TuningPresets = {
    stock = {
        id = 'stock',
        label = 'OEM Factory',
        description = 'Configuracao original de fabrica, focada em confiabilidade.',
        package = 'express',
        laborHours = 1.2,
        stockItems = {},
        requiredComponents = {},
        wearBias = 1.00,
        performanceBias = 1.00,
        modifiers = {
            enginePower = 0.00,
            brakeForce = 0.00,
            suspensionDrop = 0.00,
            tractionBias = 0.00,
        },
        mods = {
            engine = -1,
            brakes = -1,
            transmission = -1,
            suspension = -1,
            turbo = false,
        },
    },
    oem_plus = {
        id = 'oem_plus',
        label = 'OEM Plus',
        description = 'Resposta mais refinada sem sacrificar a dirigibilidade do dia a dia.',
        package = 'premium',
        laborHours = 3.4,
        stockItems = {
            ecu_map_token = 1,
            performance_filter = 1,
        },
        requiredComponents = {
            engine_block = 55,
            ignition_system = 55,
            ecu_unit = 60,
        },
        wearBias = 1.04,
        performanceBias = 1.08,
        modifiers = {
            enginePower = 0.06,
            brakeForce = 0.02,
            suspensionDrop = 0.00,
            tractionBias = 0.01,
        },
        mods = {
            engine = 1,
            brakes = 0,
            transmission = 0,
            suspension = 0,
            turbo = false,
        },
    },
    street_sport = {
        id = 'street_sport',
        label = 'Street Sport',
        description = 'Mapa esportivo, freio firme e suspensao com resposta mais direta.',
        package = 'premium',
        laborHours = 5.2,
        stockItems = {
            ecu_map_token = 1,
            performance_filter = 1,
            brake_pad_set = 1,
            alignment_shims = 1,
        },
        requiredComponents = {
            engine_block = 65,
            brake_system = 60,
            suspension_kit = 58,
            ecu_unit = 62,
        },
        wearBias = 1.10,
        performanceBias = 1.15,
        modifiers = {
            enginePower = 0.12,
            brakeForce = 0.06,
            suspensionDrop = -0.01,
            tractionBias = 0.03,
        },
        mods = {
            engine = 2,
            brakes = 1,
            transmission = 1,
            suspension = 1,
            turbo = false,
        },
    },
    circuit_rs = {
        id = 'circuit_rs',
        label = 'Circuit RS',
        description = 'Preparacao agressiva para pista, frenagem forte e resposta de giro imediata.',
        package = 'restoration',
        laborHours = 7.4,
        stockItems = {
            ecu_map_token = 1,
            turbo_core = 1,
            brake_pad_set = 2,
            alignment_shims = 2,
            performance_filter = 1,
        },
        requiredComponents = {
            engine_block = 76,
            brake_system = 74,
            gearbox = 68,
            turbocharger = 70,
            suspension_kit = 70,
        },
        wearBias = 1.22,
        performanceBias = 1.26,
        modifiers = {
            enginePower = 0.20,
            brakeForce = 0.10,
            suspensionDrop = -0.02,
            tractionBias = 0.04,
        },
        mods = {
            engine = 3,
            brakes = 2,
            transmission = 2,
            suspension = 2,
            turbo = true,
        },
    },
    drift_master = {
        id = 'drift_master',
        label = 'Drift Master',
        description = 'Geometria traseira solta, mapa agressivo e transferencia rapida.',
        package = 'premium',
        laborHours = 6.3,
        stockItems = {
            ecu_map_token = 1,
            alignment_shims = 2,
            tires = 1,
            performance_filter = 1,
        },
        requiredComponents = {
            engine_block = 70,
            drivetrain = 72,
            suspension_kit = 68,
            tires = 70,
        },
        wearBias = 1.28,
        performanceBias = 1.20,
        modifiers = {
            enginePower = 0.15,
            brakeForce = 0.05,
            suspensionDrop = -0.03,
            tractionBias = -0.04,
        },
        mods = {
            engine = 2,
            brakes = 1,
            transmission = 2,
            suspension = 3,
            turbo = true,
        },
    },
    offroad_apex = {
        id = 'offroad_apex',
        label = 'Offroad Apex',
        description = 'Elevacao, tracao progressiva e confiabilidade para terreno severo.',
        package = 'premium',
        laborHours = 5.8,
        stockItems = {
            suspension_kit = 1,
            alignment_shims = 2,
            tires = 1,
        },
        requiredComponents = {
            suspension_kit = 72,
            drivetrain = 65,
            tires = 70,
            body_structure = 60,
        },
        wearBias = 1.14,
        performanceBias = 1.14,
        modifiers = {
            enginePower = 0.08,
            brakeForce = 0.02,
            suspensionDrop = 0.03,
            tractionBias = 0.06,
        },
        mods = {
            engine = 1,
            brakes = 0,
            transmission = 1,
            suspension = -1,
            turbo = false,
        },
    },
}
